### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by szcf-weiya**
1. In IRLS.cc, refer to @timflutre 's branch fix_issue5, add the code to judge the version of GSL, and fix some typos in @timflutre 's code.

2. In test.R, before writing `y` to binary file, transform `y` from integer to double. Because in test.cpp, `gsl_vector_fread()` assumes that the elements in `y`  are double, 

```
 FILE * f = fopen(file_y.c_str(), "r");
 gsl_vector_fread(f, y);
 fclose(f);
```
while without `as.double(y)` in test.R, the elements of `y` in the binary file are integer. Then, the program would report the following error

```
gsl: fwrite_source.c:64: ERROR: fread failed
Default GSL error handler invoked.
Aborted (core dumped)
```

3. In test.cpp, it is necessary to include the head file `cstring`, otherwise, the program would report the following error.

```
error: ‘strcmp’ was not declared in this scope
```

### CODE REVIEW

**Comment by timflutre** [comment]
Hello @szcf-weiya ,

concerning your first point, I fixed the problem mentioned in issue #5, thanks to your input (see the discussion), at least on my computer. Let me know if it works on yours, too.

Concerning the second point, I already use `as.numeric(y)` for that purpose, and it's working on my computer, not on yours?

Concerning the third point, the header `cstring`is already included in `test.cpp`. Maybe you didn't retrieve the latest version of the code?

**Comment by szcf-weiya** [comment]
In fact,  the code that I checked is on the branch `master`, NOT `fix_issue5`.
After checking the code on the branch `fix_issue5`, it works well for me.

**Comment by timflutre** [comment]
Ok, perfect. I just sent an email to @xqwen.

I am closing your pull request as it is no longer necessary. You can always go back to discuss this on the page for issue #5.

**Comment by szcf-weiya** [comment]
OK!

**Comment by szcf-weiya** [comment]
@timflutre  OK!

**Pull request closed without merging**
